
const _import = require('../import-' + process.env.NODE_ENV)
const rentRouter = [
  {
    'menuId': 101,
    'parentId': 0,
    'parentName': null,
    'name': '租住管理',
    'url': '',
    'perms': null,
    'type': 0,
    'icon': 'shop',
    'orderNum': 0,
    'open': null,
    'list': [
      {
        'menuId': 102,
        'parentId': 1,
        'parentName': null,
        'name': '入住办理',
        'url': 'rent/check',
        'perms': null,
        'type': 1,
        'icon': '',
        'orderNum': 1,
        'open': null,
        'list': null,
      },
	  {
	    'menuId': 104,
	    'parentId': 1,
	    'parentName': null,
	    'name': '订单列表',
	    'url': 'rent/relet',
	    'perms': null,
	    'type': 1,
	    'icon': '',
	    'orderNum': 1,
	    'open': null,
	    'list': null,
	  },
	  {
	    'menuId': 105,
	    'parentId': 1,
	    'parentName': null,
	    'name': '租客列表',
	    'url': 'rent/retire',
	    'perms': null,
	    'type': 1,
	    'icon': '',
	    'orderNum': 1,
	    'open': null,
	    'list': null,
	  },
	  {
	    'menuId': 103,
	    'parentId': 1,
	    'parentName': null,
	    'name': '订单缴费记录',
	    'url': 'rent/all_manage',
	    'perms': null,
	    'type': 1,
	    'icon': '',
	    'orderNum': 1,
	    'open': null,
	    'list': null,
		hidden:true
	  },
	  {
	    'menuId': 106,
	    'parentId': 1,
	    'parentName': null,
	    'name': '退租订单列表',
	    'url': 'rent/all_check',
	    'perms': null,
	    'type': 1,
	    'icon': '',
	    'orderNum': 1,
	    'open': null,
	    'list': null,
	  },
	  {
	    'menuId': 107,
	    'parentId': 1,
	    'parentName': null,
	    'name': '订单续租记录',
	    'url': 'rent/change',
	    'perms': null,
	    'type': 1,
	    'icon': '',
	    'orderNum': 1,
	    'open': null,
	    'list': null,
			hidden:true
	  },
	  {
	    'menuId': 108,
	    'parentId': 1,
	    'parentName': null,
	    'name': '详情',
	    'url': 'rent/rent_deails',
	    'perms': null,
	    'type': 1,
	    'icon': '',
	    'orderNum': 1,
	    'open': null,
	    'list': null,
	  	hidden:true
	  },
	  {
	    'menuId': 98,
	    'parentId': 1,
	    'parentName': null,
	    'name': '订单详情',
	    'url': 'rent/order_deails',
	    'perms': null,
	    'type': 1,
	    'icon': '',
	    'orderNum': 1,
	    'open': null,
	    'list': null,
	  	hidden:true
	  },
		{
		  'menuId': 109,
		  'parentId': 1,
		  'parentName': null,
		  'name': '办理入住',
		  'url': 'rent/rent_in',
		  'perms': null,
		  'type': 1,
		  'icon': '',
		  'orderNum': 1,
		  'open': null,
		  'list': null,
			hidden:true
		}
    ]
  }
]

export default rentRouter